name: Deploy to Firebase Hosting

on:
  workflow_run:
    workflows: ["NodeJS CI"]
    branches: [latte-dev]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore build cache
        uses: actions/cache/restore@v3
        with:
          path: out
          key: ${{ runner.os }}-nextjs-build-

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HIMAFORKA_UAJY_ID }}"
          projectId: himaforka-uajy-id
          channelId: live
